image: node:16

pages:
  stage: deploy
  cache:
    paths:
      - inspector-view/node_modules/
  script:
    - cd inspector-view
    - npm install
    - cp .env.production .env
    - npm run build
    - cd ..
    - mkdir -p public/inspector-view
    - cp -r inspector-view/dist/* public/inspector-view/
  artifacts:
    paths:
      - public
  only:
    - table-view 